blank_issues_enabled: false
contact_links:
  - name: CTD Data Steering Committee
    url: https://github.com/orgs/dfo-mar-odis/teams/ctd-data-steering-committee
    about: Please ask and answer questions here.
